# Generated by Django 3.1.7 on 2022-10-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0011_auto_20200609_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='book',
            name='last_log',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.RemoveField(
            model_name='booklog',
            name='associated_invoice',
        ),
        migrations.RemoveField(
            model_name='booklog',
            name='parent_book',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='last_log',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='associated_invoice',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.DeleteModel(
            name='BillingProfile',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookLog',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InventoryLog',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
