# Generated by Django 3.1.7 on 2022-10-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0012_auto_20221022_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_gst_percentage',
            new_name='product_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_rate_with_gst',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
