# Generated by Django 3.1.7 on 2022-10-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0013_auto_20221022_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_code',
            field=models.CharField(default='-', max_length=200, null=True),
        ),
    ]
