# Generated by Django 3.1.7 on 2022-10-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0014_product_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='financial_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='place_of_supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='books_reflected',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='inventory_reflected',
        ),
    ]
