# Generated by Django 3.1.7 on 2022-10-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0015_auto_20221023_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter', models.CharField(max_length=150)),
            ],
        ),
    ]
