# Generated by Django 3.1.7 on 2022-10-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0016_transporter_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_phone',
        ),
    ]
