# Generated by Django 3.1.7 on 2022-10-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0017_remove_customer_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_term', models.CharField(max_length=150)),
            ],
        ),
    ]
