# Generated by Django 3.1.7 on 2022-10-24 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0018_payment_terms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
