# Generated by Django 3.1.7 on 2022-10-24 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0019_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 24, 13, 0, 17, 821514)),
        ),
    ]
